name: things

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  create-animated-gifs:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@main

      - name: stuff
        run: |
          sudo apt install ghostscript zsh
          DQT='"'
          SRC="rights=${DQT}none${DQT} pattern=${DQT}PDF${DQT}"
          RPL="rights=${DQT}read|write${DQT} pattern=${DQT}PDF${DQT}"
          sudo sed -i "s/$SRC/$RPL/" /etc/ImageMagick-6/policy.xml
          chmod +x ./colors.sh
          ./colors.sh
          chmod +x ./table.sh
          ./table.sh
          git config --local user.email "action[bot]@github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "$(od -An -tx1 -w12 -N12 /dev/urandom | cut -c2- | tr '[:lower:]' '[:upper:]')"
          git push
